name: Publish OCR-D Manager

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # run manually

env:
  REGISTRY_PATH: ghcr.io/slub

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build args
      run: |
        date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
        echo "vcs_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    - name: Build the OCR-D Manager image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_PATH }}/ocrd_manager:latest
        build-args: |
          BUILD_DATE=${{ env.build_date }}
          VCS_REF=${{ env.vcs_ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
