name: Publish OCR-D Manager and OCR-D Monitor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_PATH: ghcr.io/markusweigelt

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the OCR-D Manager image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_PATH }}/ocrd_manager:latest
        build-args: |
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          VCS_REF=$(git rev-parse --short HEAD)
        cache-from: type=gha
        cache-to: type=gha,mode=max  
    
    - name: Build the OCR-D Monitor image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: ./ocrd_monitor
        push: true
        tags: ${{ env.REGISTRY_PATH }}/ocrd_monitor:latest
        build-args: |
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          VCS_REF=$(git rev-parse --short HEAD)
        cache-from: type=gha
        cache-to: type=gha,mode=max
